export const assetsCatalog = [
  {
    id: "action_figure",
    name: "🧸 Action Figure Super",
    price: 350_000,
    minAge: 10,
    isProductive: false,
    description: "Mainan pahlawan super koleksi terbatas. Bagus untuk pajangan di kamar.",
    delta: { happy: 5, health: 0, smarts: 0, looks: 0 },
  },
  {
    id: "board_game",
    name: "🎲 Board Game Strategi",
    price: 250_000,
    minAge: 10,
    isProductive: true,
    description: "Permainan papan yang mengasah otak dan kemampuan menyusun strategi.",
    delta: { happy: 2, health: 0, smarts: 5, looks: 0 },
  },
  {
    id: "bicycle",
    name: "🚲 Sepeda BMX",
    price: 1_800_000,
    minAge: 10,
    isProductive: true,
    description: "Sepeda keren untuk keliling komplek. Membuatmu lebih bugar dan populer di antara teman.",
    delta: { happy: 10, health: 5, smarts: 0, looks: 2 },
  },
  {
    id: "game_console",
    name: "🎮 Konsol Game (Handheld)",
    price: 4_500_000,
    minAge: 10,
    isProductive: false,
    description: "Perangkat game portabel untuk bermain kapan saja. Sangat menghibur tapi jangan sampai lupa waktu.",
    delta: { happy: 15, health: -2, smarts: 2, looks: 0 },
  },
  {
    id: "smartphone_entry",
    name: "📱 Smartphone Entry-Level",
    price: 2_500_000,
    minAge: 12,
    isProductive: true,
    description: "Ponsel pintar pertama untuk berkomunikasi dan menjelajah internet.",
    delta: { happy: 8, health: 0, smarts: 4, looks: 5 },
  },
  {
    id: "sim_fast_track",
    name: "🪪 SIM (Jalur Cepat)",
    price: 1_200_000,
    minAge: 17,
    isProductive: true,
    description: "Mendapatkan SIM secara instan tanpa ujian. Mahal tapi pasti jadi.",
    delta: { happy: 5, health: 0, smarts: 0, looks: 0 },
  },
  {
    id: "laptop",
    name: "💻 Laptop Standard",
    price: 7_500_000,
    minAge: 12,
    isProductive: true,
    description: "Komputer jinjing untuk mengerjakan tugas sekolah dan proyek kreatif.",
    delta: { happy: 4, health: 0, smarts: 5, looks: 0 },
  },
  {
    id: "motorbike",
    name: "🏍️ Motor Matic",
    price: 18_000_000,
    minAge: 17,
    isProductive: true,
    description: "Kendaraan roda dua yang praktis untuk menembus kemacetan kota.",
    delta: { happy: 2, health: 0, smarts: 0, looks: 1 },
  },
  {
    id: "city_car",
    name: "🚗 Mobil City Car",
    price: 130_000_000,
    minAge: 18,
    isProductive: true,
    description: "Mobil mungil yang hemat bahan bakar, cocok untuk mahasiswa atau pekerja muda.",
    delta: { happy: 4, health: 0, smarts: 0, looks: 2 },
  },
  {
    id: "sports_car",
    name: "🏎️ Mobil Sport",
    price: 1_200_000_000,
    minAge: 20,
    isProductive: false,
    description: "Mobil mewah dengan kecepatan tinggi. Simbol kesuksesan dan gaya hidup kelas atas.",
    delta: { happy: 15, health: 0, smarts: 0, looks: 20 },
  },
  {
    id: "small_house",
    name: "🏠 Rumah Sederhana",
    price: 380_000_000,
    minAge: 21,
    isProductive: true,
    description: "Hunian nyaman dengan lingkungan yang asri. Langkah awal untuk mandiri.",
    delta: { happy: 8, health: 2, smarts: 0, looks: 2 },
  },
  {
    id: "luxury_house",
    name: "🏙️ Apartemen Mewah",
    price: 2_500_000_000,
    minAge: 25,
    isProductive: true,
    description: "Apartemen di pusat kota dengan fasilitas lengkap dan pemandangan gedung pencakar langit.",
    delta: { happy: 20, health: 5, smarts: 0, looks: 15 },
  },
];
