export const educationCatalog = [
  {
    id: "elementary",
    name: "SD",
    minAge: 6,
    costPerYear: 0,
    yearsToComplete: 6,
    smartsPerYear: 3,
    jobBoost: 0,
  },
  {
    id: "junior_high",
    name: "SMP",
    minAge: 12,
    costPerYear: 0,
    yearsToComplete: 3,
    smartsPerYear: 4,
    jobBoost: 2,
  },
  {
    id: "high_school",
    name: "SMA",
    minAge: 15,
    costPerYear: 0,
    yearsToComplete: 3,
    smartsPerYear: 5,
    jobBoost: 8,
  },
  {
    id: "ged",
    name: "Ujian Kesetaraan (GED)",
    minAge: 16,
    costPerYear: 15_000_000,
    yearsToComplete: 0,
    smartsPerYear: 2,
    jobBoost: 4,
    requirement: (state) => !state.education.completed.includes("high_school"),
  },
  {
    id: "college_cs",
    name: "Universitas - Sains Komputer",
    minAge: 18,
    costPerYear: 36_000_000,
    yearsToComplete: 4,
    smartsPerYear: 7,
    jobBoost: 16,
    major: "computer_science",
  },
  {
    id: "college_finance",
    name: "Universitas - Keuangan",
    minAge: 18,
    costPerYear: 40_000_000,
    yearsToComplete: 4,
    smartsPerYear: 6,
    jobBoost: 14,
    major: "finance",
  },
];
