export const educationCatalog = [
  {
    id: "elementary",
    name: "Sekolah Dasar (SD)",
    minAge: 6,
    maxAge: 12,
    costPerYear: 0,
    yearsToComplete: 6,
    smartsPerYear: 3,
    jobBoost: 0,
  },
  {
    id: "junior_high",
    name: "SMP",
    minAge: 12,
    maxAge: 15,
    costPerYear: 0,
    yearsToComplete: 3,
    smartsPerYear: 4,
    jobBoost: 2,
  },
  {
    id: "high_school",
    name: "SMA",
    minAge: 15,
    maxAge: 18,
    costPerYear: 0,
    yearsToComplete: 3,
    smartsPerYear: 5,
    jobBoost: 8,
  },
  {
    id: "paket_b",
    name: "Program Paket B (Setara SMP)",
    minAge: 17,
    costPerYear: 5_000_000,
    yearsToComplete: 1,
    smartsPerYear: 2,
    jobBoost: 2,
    requirement: (state) => !state.education.completed.includes("junior_high") && state.education.completed.includes("elementary"),
  },
  {
    id: "paket_c",
    name: "Program Paket C (Setara SMA)",
    minAge: 20,
    costPerYear: 8_000_000,
    yearsToComplete: 1,
    smartsPerYear: 3,
    jobBoost: 6,
    requirement: (state) => !state.education.completed.includes("high_school") && state.education.completed.includes("junior_high"),
  },
  {
    id: "university_ptn",
    name: "Universitas Negeri (PTN)",
    minAge: 18,
    costPerYear: 15_000_000,
    yearsToComplete: 4,
    smartsPerYear: 8,
    jobBoost: 20,
  },
  {
    id: "university_swasta",
    name: "Universitas Swasta",
    minAge: 18,
    costPerYear: 45_000_000,
    yearsToComplete: 4,
    smartsPerYear: 6,
    jobBoost: 15,
  },
];
