export const educationCatalog = [
  {
    id: "elementary",
    name: "Sekolah Dasar (SD)",
    minAge: 6,
    maxAge: 13,
    costPerYear: 0,
    yearsToComplete: 6,
    smartsPerYear: 3,
    jobBoost: 0,
  },
  {
    id: "junior_high",
    name: "SMP",
    minAge: 12,
    maxAge: 17,
    costPerYear: 0,
    yearsToComplete: 3,
    smartsPerYear: 4,
    jobBoost: 2,
  },
  {
    id: "high_school",
    name: "SMA",
    minAge: 15,
    maxAge: 21,
    costPerYear: 0,
    yearsToComplete: 3,
    smartsPerYear: 5,
    jobBoost: 8,
  },
  {
    id: "paket_b",
    name: "Program Paket B (Setara SMP)",
    minAge: 17,
    costPerYear: 5_000_000,
    yearsToComplete: 1,
    smartsPerYear: 2,
    jobBoost: 2,
    requirement: (state) => !state.education.completed.includes("junior_high") && state.education.completed.includes("elementary"),
  },
  {
    id: "paket_c",
    name: "Program Paket C (Setara SMA)",
    minAge: 20,
    costPerYear: 8_000_000,
    yearsToComplete: 1,
    smartsPerYear: 3,
    jobBoost: 6,
    requirement: (state) => !state.education.completed.includes("high_school") && state.education.completed.includes("junior_high"),
  },
  {
    id: "college_cs",
    name: "Universitas - Sains Komputer",
    minAge: 18,
    costPerYear: 36_000_000,
    yearsToComplete: 4,
    smartsPerYear: 7,
    jobBoost: 16,
    major: "computer_science",
  },
  {
    id: "college_finance",
    name: "Universitas - Keuangan",
    minAge: 18,
    costPerYear: 40_000_000,
    yearsToComplete: 4,
    smartsPerYear: 6,
    jobBoost: 14,
    major: "finance",
  },
];
