export const jobsCatalog = [
  {
    id: "ngamen",
    name: "Pengamen Jalanan",
    track: "underage",
    tier: 1,
    minAge: 12,
    minSmarts: 0,
    salaryPerYear: 3_000_000,
    delta: { happy: -2, health: -2, smarts: 0, looks: -1 },
  },
  {
    id: "newspaper_boy",
    name: "Loper Koran",
    track: "underage",
    tier: 1,
    minAge: 12,
    minSmarts: 10,
    salaryPerYear: 4_500_000,
    delta: { happy: -1, health: -1, smarts: 1, looks: -1 },
  },
  {
    id: "warung_keeper",
    name: "Penjaga Warung",
    track: "underage",
    tier: 1,
    minAge: 14,
    minSmarts: 15,
    salaryPerYear: 6_000_000,
    delta: { happy: 0, health: -1, smarts: 2, looks: 0 },
  },
  {
    id: "cleaner",
    name: "Petugas Kebersihan",
    track: "service",
    tier: 1,
    minAge: 18,
    minSmarts: 10,
    salaryPerYear: 42_000_000,
    promotionAfterYears: 4,
    nextJobId: "field_supervisor",
    delta: { happy: -1, health: -2, smarts: 1, looks: -1 },
  },
  {
    id: "farmer",
    name: "Petani",
    track: "service",
    tier: 1,
    minAge: 18,
    minSmarts: 15,
    salaryPerYear: 48_000_000,
    delta: { happy: 2, health: 1, smarts: 0, looks: -2 },
  },
  {
    id: "security",
    name: "Satpam",
    track: "service",
    tier: 1,
    minAge: 19,
    minSmarts: 20,
    salaryPerYear: 54_000_000,
    delta: { happy: 0, health: 0, smarts: 1, looks: 2 },
  },
  {
    id: "police",
    name: "Polisi",
    track: "law",
    tier: 1,
    minAge: 20,
    minSmarts: 48,
    cleanRecordRequired: true,
    salaryPerYear: 78_000_000,
    promotionAfterYears: 4,
    nextJobId: "detective",
    delta: { happy: -1, health: -3, smarts: 1, looks: 0 },
  },
  {
    id: "detective",
    name: "Detektif",
    track: "law",
    tier: 2,
    minAge: 25,
    minSmarts: 62,
    cleanRecordRequired: true,
    salaryPerYear: 124_000_000,
    delta: { happy: 1, health: -2, smarts: 3, looks: 1 },
  },
  {
    id: "jr_dev",
    name: "Junior App Developer",
    track: "tech",
    tier: 1,
    minAge: 20,
    minSmarts: 58,
    requiredMajor: "computer_science",
    salaryPerYear: 96_000_000,
    promotionAfterYears: 3,
    nextJobId: "sr_dev",
    delta: { happy: 0, health: -1, smarts: 3, looks: 0 },
  },
  {
    id: "sr_dev",
    name: "Senior App Developer",
    track: "tech",
    tier: 2,
    minAge: 24,
    minSmarts: 72,
    requiredMajor: "computer_science",
    salaryPerYear: 186_000_000,
    delta: { happy: 1, health: -1, smarts: 2, looks: 1 },
  },
  {
    id: "banker",
    name: "Banker",
    track: "finance",
    tier: 1,
    minAge: 22,
    minSmarts: 65,
    requiredMajor: "finance",
    cleanRecordRequired: true,
    salaryPerYear: 132_000_000,
    promotionAfterYears: 4,
    nextJobId: "sr_banker",
    delta: { happy: 0, health: -2, smarts: 2, looks: 1 },
  },
  {
    id: "sr_banker",
    name: "Senior Banker",
    track: "finance",
    tier: 2,
    minAge: 27,
    minSmarts: 78,
    requiredMajor: "finance",
    cleanRecordRequired: true,
    salaryPerYear: 228_000_000,
    delta: { happy: 1, health: -2, smarts: 2, looks: 1 },
  },
  {
    id: "apprentice_cameraman",
    name: "Kameramen Magang",
    track: "media",
    tier: 1,
    minAge: 18,
    minSmarts: 30,
    salaryPerYear: 36_000_000,
    promotionAfterYears: 2,
    nextJobId: "cameraman",
    delta: { happy: 2, health: -1, smarts: 1, looks: 1 },
  },
  {
    id: "cameraman",
    name: "Kameramen",
    track: "media",
    tier: 2,
    minAge: 20,
    minSmarts: 45,
    salaryPerYear: 72_000_000,
    delta: { happy: 5, health: -2, smarts: 2, looks: 2 },
  },
];
