export const jobsCatalog = [
  {
    id: "ngamen",
    name: "Pengamen Jalanan",
    type: "full-time",
    track: "informal",
    tier: 1,
    minAge: 12,
    minSmarts: 0,
    salaryPerYear: 1_440_000,
    maxWealthStatus: "middle",
    delta: { happy: -2, health: -2, smarts: 0, looks: -1 },
  },
  {
    id: "parking_attendant",
    name: "Tukang Parkir",
    type: "full-time",
    track: "informal",
    tier: 1,
    minAge: 15,
    minSmarts: 5,
    salaryPerYear: 4_320_000,
    maxWealthStatus: "middle",
    delta: { happy: -3, health: -2, smarts: 1, looks: -2 },
  },
  {
    id: "newspaper_boy",
    name: "Loper Koran",
    type: "full-time",
    track: "informal",
    tier: 1,
    minAge: 12,
    minSmarts: 10,
    salaryPerYear: 2_880_000,
    maxWealthStatus: "middle",
    delta: { happy: -1, health: -1, smarts: 1, looks: -1 },
  },
  {
    id: "warung_keeper",
    name: "Penjaga Warung",
    type: "full-time",
    track: "service",
    tier: 1,
    minAge: 14,
    minSmarts: 15,
    salaryPerYear: 7_200_000,
    maxWealthStatus: "middle",
    delta: { happy: 0, health: -1, smarts: 2, looks: 0 },
  },
  {
    id: "waiter",
    name: "Pelayan Restoran",
    type: "full-time",
    track: "service",
    tier: 1,
    minAge: 17,
    minSmarts: 20,
    salaryPerYear: 21_600_000,
    promotionAfterYears: 3,
    nextJobId: "head_waiter",
    delta: { happy: -2, health: -3, smarts: 2, looks: 5 },
  },
  {
    id: "head_waiter",
    name: "Kepala Pelayan",
    type: "full-time",
    track: "service",
    tier: 2,
    minAge: 20,
    minSmarts: 35,
    salaryPerYear: 43_200_000,
    delta: { happy: 2, health: -2, smarts: 3, looks: 5 },
  },
  {
    id: "admin_staff",
    name: "Staff Administrasi",
    type: "full-time",
    track: "corporate",
    tier: 1,
    minAge: 18,
    minSmarts: 40,
    salaryPerYear: 50_400_000,
    promotionAfterYears: 5,
    nextJobId: "manager",
    delta: { happy: -5, health: -1, smarts: 4, looks: 2 },
  },
  {
    id: "manager",
    name: "Manajer Operasional",
    type: "full-time",
    track: "corporate",
    tier: 2,
    minAge: 25,
    minSmarts: 65,
    salaryPerYear: 100_800_000,
    promotionAfterYears: 6,
    nextJobId: "ceo",
    delta: { happy: -10, health: -5, smarts: 10, looks: 5 },
  },
  {
    id: "ceo",
    name: "Direktur Utama (CEO)",
    type: "full-time",
    track: "corporate",
    tier: 3,
    minAge: 35,
    minSmarts: 85,
    salaryPerYear: 360_000_000,
    delta: { happy: 15, health: -10, smarts: 20, looks: 15 },
  },
  {
    id: "tutor",
    name: "Guru Les Privat",
    type: "full-time",
    track: "education",
    tier: 1,
    minAge: 16,
    minSmarts: 60,
    salaryPerYear: 11_520_000,
    delta: { happy: 5, health: -1, smarts: 8, looks: 0 },
  },
  {
    id: "teacher",
    name: "Guru Sekolah",
    type: "full-time",
    track: "education",
    tier: 2,
    minAge: 22,
    minSmarts: 65,
    requiredMajor: "education",
    salaryPerYear: 64_800_000,
    promotionAfterYears: 8,
    nextJobId: "principal",
    delta: { happy: 10, health: -2, smarts: 5, looks: 2 },
  },
  {
    id: "principal",
    name: "Kepala Sekolah",
    type: "full-time",
    track: "education",
    tier: 3,
    minAge: 35,
    minSmarts: 75,
    salaryPerYear: 129_600_000,
    delta: { happy: 5, health: -5, smarts: 10, looks: 5 },
  },
  {
    id: "nurse",
    name: "Perawat",
    type: "full-time",
    track: "medical",
    tier: 1,
    minAge: 22,
    minSmarts: 60,
    requiredMajor: "nursing",
    salaryPerYear: 72_000_000,
    delta: { happy: -5, health: -5, smarts: 10, looks: 0 },
  },
  {
    id: "doctor",
    name: "Dokter Umum",
    type: "full-time",
    track: "medical",
    tier: 2,
    minAge: 26,
    minSmarts: 85,
    requiredMajor: "medicine",
    salaryPerYear: 187_200_000,
    promotionAfterYears: 10,
    nextJobId: "specialist_doctor",
    delta: { happy: -10, health: -5, smarts: 15, looks: 5 },
  },
  {
    id: "specialist_doctor",
    name: "Dokter Spesialis",
    type: "full-time",
    track: "medical",
    tier: 3,
    minAge: 32,
    minSmarts: 95,
    requiredMajor: "medicine",
    salaryPerYear: 504_000_000,
    delta: { happy: 10, health: -10, smarts: 20, looks: 10 },
  },
  {
    id: "police",
    name: "Polisi",
    type: "full-time",
    track: "law",
    tier: 1,
    minAge: 20,
    minSmarts: 48,
    cleanRecordRequired: true,
    salaryPerYear: 57_600_000,
    promotionAfterYears: 4,
    nextJobId: "detective",
    delta: { happy: -1, health: -3, smarts: 1, looks: 0 },
  },
  {
    id: "detective",
    name: "Detektif",
    type: "full-time",
    track: "law",
    tier: 2,
    minAge: 25,
    minSmarts: 62,
    cleanRecordRequired: true,
    salaryPerYear: 100_800_000,
    delta: { happy: 1, health: -2, smarts: 3, looks: 1 },
  },
  {
    id: "jr_dev",
    name: "Junior App Developer",
    type: "full-time",
    track: "tech",
    tier: 1,
    minAge: 20,
    minSmarts: 58,
    requiredMajor: "computer_science",
    salaryPerYear: 86_400_000,
    promotionAfterYears: 3,
    nextJobId: "sr_dev",
    delta: { happy: 0, health: -1, smarts: 3, looks: 0 },
  },
  {
    id: "sr_dev",
    name: "Senior App Developer",
    type: "full-time",
    track: "tech",
    tier: 2,
    minAge: 24,
    minSmarts: 72,
    requiredMajor: "computer_science",
    salaryPerYear: 144_000_000,
    delta: { happy: 1, health: -1, smarts: 2, looks: 1 },
  },
  // --- PART-TIME JOBS ---
  {
    id: "pt_barista",
    name: "Barista Part-time",
    type: "part-time",
    track: "service",
    tier: 1,
    minAge: 16,
    minSmarts: 20,
    salaryPerYear: 9_600_000, // Rp800k/bln
    delta: { happy: 5, health: -2, smarts: 5, looks: 10 },
  },
  {
    id: "pt_cashier",
    name: "Kasir Minimarket (Part-time)",
    type: "part-time",
    track: "service",
    tier: 1,
    minAge: 15,
    minSmarts: 25,
    salaryPerYear: 7_200_000, // Rp600k/bln
    delta: { happy: -2, health: -3, smarts: 8, looks: 0 },
  },
  {
    id: "pt_library_helper",
    name: "Asisten Perpustakaan (Part-time)",
    type: "part-time",
    track: "education",
    tier: 1,
    minAge: 14,
    minSmarts: 40,
    salaryPerYear: 6_000_000, // Rp500k/bln
    delta: { happy: 10, health: 0, smarts: 15, looks: 0 },
  },
  {
    id: "banker",
    name: "Banker",
    track: "finance",
    tier: 1,
    minAge: 22,
    minSmarts: 65,
    requiredMajor: "finance",
    cleanRecordRequired: true,
    salaryPerYear: 132_000_000,
    promotionAfterYears: 4,
    nextJobId: "sr_banker",
    delta: { happy: 0, health: -2, smarts: 2, looks: 1 },
  },
  {
    id: "sr_banker",
    name: "Senior Banker",
    track: "finance",
    tier: 2,
    minAge: 27,
    minSmarts: 78,
    requiredMajor: "finance",
    cleanRecordRequired: true,
    salaryPerYear: 228_000_000,
    delta: { happy: 1, health: -2, smarts: 2, looks: 1 },
  },
  {
    id: "apprentice_cameraman",
    name: "Kameramen Magang",
    track: "media",
    tier: 1,
    minAge: 18,
    minSmarts: 30,
    salaryPerYear: 36_000_000,
    promotionAfterYears: 2,
    nextJobId: "cameraman",
    delta: { happy: 2, health: -1, smarts: 1, looks: 1 },
  },
  {
    id: "cameraman",
    name: "Kameramen",
    track: "media",
    tier: 2,
    minAge: 20,
    minSmarts: 45,
    salaryPerYear: 72_000_000,
    delta: { happy: 5, health: -2, smarts: 2, looks: 2 },
  },
];
